# ~/.config/.tmux.conf

unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style "bg=#333333 fg=#5eacd3"
set -g status-right "#(basename $(pwd)) | %H:%M %b %d %Y"
set-option -g default-terminal "tmux-256color"
set -sg escape-time 0 # terminal app emulator, please know: `<Escape>` is not `<Meta>`. `<Escape>` is `<Escape>`.

set-window-option -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection

# vim-like pane switching
bind -r ^ last-window
bind -r k select-pane -U
bind -r j select-pane -D
bind -r h select-pane -L
bind -r l select-pane -R

# vim-like resize panes
bind -n M-h resize-pane -L 5
bind -n M-j resize-pane -D 5
bind -n M-k resize-pane -U 5
bind -n M-l resize-pane -R 5

# yank em
bind-key -T copy-mode-vi v send-keys -X begin-selection
# if terminal has OSC 52 clipboard support: set -s set-clipboard on 
# else: bind-key -T copy-mode-vi y send-keys -X copy-pipe "xclip -selection clipboard -in"
